/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedSpacesIndexRouteImport } from './routes/_authenticated/spaces/index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiNotificationsRegisterRouteImport } from './routes/api/notifications/register'
import { Route as ApiIngestEmailRouteImport } from './routes/api/ingest/email'
import { Route as AuthenticatedSpacesSpaceIdRouteImport } from './routes/_authenticated/spaces/$spaceId'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties/new'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties/$propertyId'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items/new'
import { Route as AuthenticatedItemsItemIdRouteImport } from './routes/_authenticated/items/$itemId'
import { Route as AuthenticatedPropertiesPropertyIdIndexRouteImport } from './routes/_authenticated/properties/$propertyId/index'
import { Route as AuthenticatedPropertiesPropertyIdSpacesIndexRouteImport } from './routes/_authenticated/properties/$propertyId/spaces/index'
import { Route as AuthenticatedPropertiesPropertyIdItemsIndexRouteImport } from './routes/_authenticated/properties/$propertyId/items/index'
import { Route as AuthenticatedPropertiesPropertyIdSpacesSpaceIdRouteImport } from './routes/_authenticated/properties/$propertyId/spaces/$spaceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpacesIndexRoute =
  AuthenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRegisterRoute =
  ApiNotificationsRegisterRouteImport.update({
    id: '/api/notifications/register',
    path: '/api/notifications/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIngestEmailRoute = ApiIngestEmailRouteImport.update({
  id: '/api/ingest/email',
  path: '/api/ingest/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpacesSpaceIdRoute =
  AuthenticatedSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsItemIdRoute =
  AuthenticatedItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdIndexRoute =
  AuthenticatedPropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdSpacesIndexRoute =
  AuthenticatedPropertiesPropertyIdSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdItemsIndexRoute =
  AuthenticatedPropertiesPropertyIdItemsIndexRouteImport.update({
    id: '/items/',
    path: '/items/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute =
  AuthenticatedPropertiesPropertyIdSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRoute
  '/api/ingest/email': typeof ApiIngestEmailRoute
  '/api/notifications/register': typeof ApiNotificationsRegisterRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/properties/$propertyId/': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/properties/$propertyId/spaces/$spaceId': typeof AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute
  '/properties/$propertyId/items/': typeof AuthenticatedPropertiesPropertyIdItemsIndexRoute
  '/properties/$propertyId/spaces/': typeof AuthenticatedPropertiesPropertyIdSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRoute
  '/api/ingest/email': typeof ApiIngestEmailRoute
  '/api/notifications/register': typeof ApiNotificationsRegisterRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/spaces': typeof AuthenticatedSpacesIndexRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/properties/$propertyId/spaces/$spaceId': typeof AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute
  '/properties/$propertyId/items': typeof AuthenticatedPropertiesPropertyIdItemsIndexRoute
  '/properties/$propertyId/spaces': typeof AuthenticatedPropertiesPropertyIdSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/items/$itemId': typeof AuthenticatedItemsItemIdRoute
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdRoute
  '/api/ingest/email': typeof ApiIngestEmailRoute
  '/api/notifications/register': typeof ApiNotificationsRegisterRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/_authenticated/properties/$propertyId/': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/_authenticated/properties/$propertyId/spaces/$spaceId': typeof AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute
  '/_authenticated/properties/$propertyId/items/': typeof AuthenticatedPropertiesPropertyIdItemsIndexRoute
  '/_authenticated/properties/$propertyId/spaces/': typeof AuthenticatedPropertiesPropertyIdSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/capture'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/inventory'
    | '/review'
    | '/settings'
    | '/auth/callback'
    | '/items/$itemId'
    | '/items/new'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/spaces/$spaceId'
    | '/api/ingest/email'
    | '/api/notifications/register'
    | '/api/v1/$'
    | '/properties/'
    | '/spaces/'
    | '/properties/$propertyId/'
    | '/properties/$propertyId/spaces/$spaceId'
    | '/properties/$propertyId/items/'
    | '/properties/$propertyId/spaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/capture'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/inventory'
    | '/review'
    | '/settings'
    | '/auth/callback'
    | '/items/$itemId'
    | '/items/new'
    | '/properties/new'
    | '/spaces/$spaceId'
    | '/api/ingest/email'
    | '/api/notifications/register'
    | '/api/v1/$'
    | '/properties'
    | '/spaces'
    | '/properties/$propertyId'
    | '/properties/$propertyId/spaces/$spaceId'
    | '/properties/$propertyId/items'
    | '/properties/$propertyId/spaces'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/capture'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/inventory'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/_authenticated/items/$itemId'
    | '/_authenticated/items/new'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/new'
    | '/_authenticated/spaces/$spaceId'
    | '/api/ingest/email'
    | '/api/notifications/register'
    | '/api/v1/$'
    | '/_authenticated/properties/'
    | '/_authenticated/spaces/'
    | '/_authenticated/properties/$propertyId/'
    | '/_authenticated/properties/$propertyId/spaces/$spaceId'
    | '/_authenticated/properties/$propertyId/items/'
    | '/_authenticated/properties/$propertyId/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiIngestEmailRoute: typeof ApiIngestEmailRoute
  ApiNotificationsRegisterRoute: typeof ApiNotificationsRegisterRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/': {
      id: '/_authenticated/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthenticatedSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/register': {
      id: '/api/notifications/register'
      path: '/api/notifications/register'
      fullPath: '/api/notifications/register'
      preLoaderRoute: typeof ApiNotificationsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/email': {
      id: '/api/ingest/email'
      path: '/api/ingest/email'
      fullPath: '/api/ingest/email'
      preLoaderRoute: typeof ApiIngestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/spaces/$spaceId': {
      id: '/_authenticated/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId': {
      id: '/_authenticated/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$propertyId/': {
      id: '/_authenticated/properties/$propertyId/'
      path: '/'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/spaces/': {
      id: '/_authenticated/properties/$propertyId/spaces/'
      path: '/spaces'
      fullPath: '/properties/$propertyId/spaces/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/items/': {
      id: '/_authenticated/properties/$propertyId/items/'
      path: '/items'
      fullPath: '/properties/$propertyId/items/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdItemsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/spaces/$spaceId': {
      id: '/_authenticated/properties/$propertyId/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/properties/$propertyId/spaces/$spaceId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdSpacesSpaceIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
  }
}

interface AuthenticatedPropertiesPropertyIdRouteChildren {
  AuthenticatedPropertiesPropertyIdIndexRoute: typeof AuthenticatedPropertiesPropertyIdIndexRoute
  AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute: typeof AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute
  AuthenticatedPropertiesPropertyIdItemsIndexRoute: typeof AuthenticatedPropertiesPropertyIdItemsIndexRoute
  AuthenticatedPropertiesPropertyIdSpacesIndexRoute: typeof AuthenticatedPropertiesPropertyIdSpacesIndexRoute
}

const AuthenticatedPropertiesPropertyIdRouteChildren: AuthenticatedPropertiesPropertyIdRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdIndexRoute:
      AuthenticatedPropertiesPropertyIdIndexRoute,
    AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute:
      AuthenticatedPropertiesPropertyIdSpacesSpaceIdRoute,
    AuthenticatedPropertiesPropertyIdItemsIndexRoute:
      AuthenticatedPropertiesPropertyIdItemsIndexRoute,
    AuthenticatedPropertiesPropertyIdSpacesIndexRoute:
      AuthenticatedPropertiesPropertyIdSpacesIndexRoute,
  }

const AuthenticatedPropertiesPropertyIdRouteWithChildren =
  AuthenticatedPropertiesPropertyIdRoute._addFileChildren(
    AuthenticatedPropertiesPropertyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedItemsItemIdRoute: typeof AuthenticatedItemsItemIdRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedSpacesSpaceIdRoute: typeof AuthenticatedSpacesSpaceIdRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedSpacesIndexRoute: typeof AuthenticatedSpacesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedItemsItemIdRoute: AuthenticatedItemsItemIdRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRouteWithChildren,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedSpacesSpaceIdRoute: AuthenticatedSpacesSpaceIdRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedSpacesIndexRoute: AuthenticatedSpacesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiIngestEmailRoute: ApiIngestEmailRoute,
  ApiNotificationsRegisterRoute: ApiNotificationsRegisterRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
